###############login logout################
USERNAME_INPUT = "USERNAME_INPUT"
PASSWORD_INPUT = "PASSWORD_INPUT"
GOTO_ACCOUNTSETTINGS = "GOTO_ACCOUNTSETTINGS"

###############cluster management ################
GOTO_CLUSTERMGMT="GOTO_CLUSTERMGMT"
GOTO_CLUSTERSETTING = "GOTO_CLUSTERSETTING"
CLUSTER_ADD_SERVER_BUTTON = "CLUSTER_ADD_SERVER_BUTTON"
GOTO_EVENTLOGS ="GOTO_EVENTLOGS"
AUDIT_LOGS_BTN = "AUDIT_LOGS_BTN"


###############osd status ######################
GOTO_OSD = "GOTO_OSD"


###############pool management#####################
GOTO_STORAGEPOOLS = "GOTO_STORAGEPOOLS"
GOTO_POOLMANAGEMENT = "GOTO_POOLMANAGEMENT"
GOTO_DEVICELIST = "GOTO_DEVICELIST"


###############UI setting########################
GOTO_SYSTEMSETTING = "GOTO_SYSTEMSETTING"
GOTO_SYSTEMSETUP = "GOTO_SYSTEMSETUP"
GOTO_USERMANAGEMENT = "GOTO_USERMANAGEMENT"